function(print_variables_matching_pattern pattern)
    message(STATUS "Variables matching pattern '${pattern}':")
    get_cmake_property(_allVariables VARIABLES)
    list(SORT _allVariables)
    foreach(_varName IN LISTS _allVariables)
        string(REGEX MATCH "${pattern}" _matchResult "${_varName}")
        if(_matchResult)
            message(STATUS "${_varName}=${${_varName}}")
        endif()
    endforeach()
endfunction()
